### ISSUE TITLE
gg_* plots with faceting not working in gwidgets' cairodevice

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZight#200]

**Comment by daniel-barnett** [comment]
Is this still an issue? It seems to work for me. 

Granted, there is an issue with background colours on the facet labels for all but the first label

**Comment by tmelliott** [comment]
I honestly can't remember if this is something I ran into, or just making a note from one of our emails with Chris. Tagged with question to come back to later.

**Comment by tmelliott** [comment]
Check on
- [ ] linux
- [ ] windows

**Comment by tmelliott** [comment]
This appears to be an issue with `cairoDevice::Cairo` on windows where parts of the plot (`gtable`, perhaps?) are being missed out and not drawn. Graphs work fine in the normal R graphics window, AND when `cairoDevice::Cairo()` is called _and then closed_!

So, not an iNZight issue - closing.
