### ISSUE TITLE
Importing datasets with large number of columns

### ISSUE THREAD

**Issue by daniel-barnett** [iNZightVIT/iNZight#287]
The preview table takes a long time to generate when there are a large number of columns. 

Once the preview shows up, clicking the import button imports the data OK (and is fast enough - 2 secs or so). 

What are your thoughts on having a checkbox to toggle the preview on/off or some heuristic that disables the preview in these cases? Maybe disabled for a start and then a button that will generate it with a warning that it may take a minute.

**Comment by tmelliott** [comment]
We could do something similar to what is done with the main view widget, and if it has more than 20(?) columns (can experiment with what is fast enough to load) disable for now and someday in the future have it display two columns: one for the variable name, the other for type (so there's still the option of overriding variable types). This will be faster until some point when there become lots and lots of rows ... :man_shrugging: 
https://github.com/iNZightVIT/iNZight/blob/6323476fb5f4476272ee07004158d089b8b4812f/R/iNZGUI.R#L212-L213
https://github.com/iNZightVIT/iNZight/blob/6323476fb5f4476272ee07004158d089b8b4812f/R/iNZDataViewWidget.R#L64-L65
