### ISSUE TITLE
Test Framework and Test-based development

### ISSUE THREAD

**Issue by scubamaggo** [iNZightVIT/iNZight#40]
Hi guys,

while scimming through the project I noticed that we hardly use any test cases. I looked around a bit for test frameworks in R and found 2 that sound promising:
RUnit: http://cran.r-project.org/web/packages/RUnit/index.html
svUnit: http://cran.r-project.org/web/packages/svUnit/
It looks like svUnit tries to accomplish much the same as RUnit but provides the ability to use the framework in the SciViews and Komodo IDE. As far as I know none of us use these IDE's, so I'd suggest giving RUnit a shot first. Both packages provide a vignette that not only explain how to use the package, but also outline the importance of testing a bit, in case you are curious. Personally I've been working for a Software Development company since the beginning of this year and having a reliable test environment is probably the single most important thing in a big software project.
Anyways, if you guys like the idea I can try to incorporate a test framework into the iNZight GUI package so that it could be used a little bit as a guideline. I don't have ample of time though, so the process might not be super quick.

Cheers,
Marco

**Comment by tmelliott** [comment]
*finally closes*
