### ISSUE TITLE
Upgrade to dplyr 1 and tidyr 1 verbs ?

### ISSUE THREAD

**Issue by ericemc3** [iNZightVIT/iNZight#404]
Accessing generated R Code is a great feature, that can really help to learn R and the tidyverse or build some scripts with minimal effort.

But since 2019/2020, few verbs i can see used in the generated code are now superseded : gather, spread, mutate_at (all verbs in _at, _if or _all)
Their replacements (pivot_longer/pivot_wider, across...) are also faster and constantly optimized.

**Comment by tmelliott** [comment]
Thanks Eric - the iNZightTools package where these are handled is a bit out-of-date now, hopefully I'll have time this year to give the package a full makeover :)

**Comment by tmelliott** [comment]
Closed with latest dev build (iNZightTools)
