### ISSUE TITLE
Error when loading package

### ISSUE THREAD

**Issue by chris-park** [iNZightVIT/iNZight#41]
I get the following error/warning messages when I load the iNZight package:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘car’
In addition: Warning messages:
1: replacing previous import by ‘survey::svydesign’ when loading ‘non-package environment’ 
2: replacing previous import by ‘survey::svysmooth’ when loading ‘non-package environment’

**Comment by tmelliott** [comment]
I think this is fixed ...?
